### ISSUE TITLE
Quicksearch triggerd in inputs with shift+k

### ISSUE THREAD

**Issue by georgebuciuman** [tokens-studio/graph-engine#250]
When pressing `shift + k` in an input it triggers the quick search, this also triggers again inside the quick search itself.
`Esc` also doesn't close quick search

https://github.com/tokens-studio/graph-engine/assets/270286/e1338494-170a-478a-ac63-54d7056cc3de

**Comment by mck** [comment]
When having to graphs open i end up with two quick search windows

![Image](https://github.com/tokens-studio/graph-engine/assets/270286/e307d7d0-17ad-4bb8-ab51-ef49615bfec2)

**Comment by georgebuciuman** [comment]
Found another bug on the shift+k window. If you have multiple graphs, it not only shows multiple search windows but when you add a new node it will always be added on the latest open graph, not on the current selected graph.
